version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"

  trino:
    build: ./bi-solution/trino-config
    container_name: trino
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  cube:
    build: ./bi-solution/ecommerce-cube
    container_name: cube
    restart: always
    environment:
      - CUBEJS_DB_HOST=mysql
      - CUBEJS_DB_NAME=demo
      - CUBEJS_DB_USER=root
      - CUBEJS_DB_PASS=root
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_API_SECRET=secret
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - trino

  superset:
    build: ./bi-solution/superset
    container_name: superset
    restart: always
    environment:
      SUPERSET_SECRET_KEY: "mysecretkey"
    ports:
      - "8088:8088"
    depends_on:
      - trino
      - mysql
