services:
  # MySQL Database
  - type: pserv
    name: mysql-db
    env: docker
    dockerfilePath: ./mysql/Dockerfile
    dockerContext: ./mysql
    plan: standard
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: ecommerce_bi
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10

  # Trino Query Engine
  - type: web
    name: trino-service
    env: docker
    dockerfilePath: ./trino/Dockerfile
    dockerContext: ./trino
    plan: standard
    envVars:
      - key: MYSQL_HOST
        fromService:
          name: mysql-db
          type: pserv
          property: host
      - key: MYSQL_PORT
        value: "3306"
    healthCheckPath: /v1/info

  # Cube.js Semantic Layer
  - type: web
    name: cube-service
    env: docker
    dockerfilePath: ./cube/Dockerfile
    dockerContext: ./cube
    plan: standard
    envVars:
      - key: CUBEJS_DB_TYPE
        value: trino
      - key: CUBEJS_DB_HOST
        fromService:
          name: trino-service
          type: web
          property: host
      - key: CUBEJS_DB_PORT
        value: "8080"
      - key: CUBEJS_DB_PRESTO_CATALOG
        value: mysql
      - key: CUBEJS_DB_NAME
        value: ecommerce_bi
      - key: CUBEJS_DB_USER
        value: cube_user
      - key: CUBEJS_API_SECRET
        generateValue: true
      - key: CUBEJS_DEV_MODE
        value: "false"
      - key: CUBEJS_PG_SQL_PORT
        value: "5439"
      - key: CUBEJS_SQL_USER
        value: superset_user
      - key: CUBEJS_SQL_PASSWORD
        value: superset_pass
      - key: CUBEJS_PRE_AGGREGATIONS_SCHEMA
        value: cube_preagg
      - key: PORT
        value: "5000"

  # Apache Superset
  - type: web
    name: superset-service
    env: docker
    dockerfilePath: ./superset/Dockerfile
    dockerContext: ./superset
    plan: standard
    envVars:
      - key: SUPERSET_SECRET_KEY
        generateValue: true
      - key: SUPERSET_CONFIG_PATH
        value: /app/pythonpath/superset_config.py
      - key: CUBE_HOST
        fromService:
          name: cube-service
          type: web
          property: host
      - key: CUBE_PORT
        value: "5439"
      - key: TRINO_HOST
        fromService:
          name: trino-service
          type: web
          property: host
      - key: TRINO_PORT
        value: "8080"